<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ProjectAgil</RootNamespace>
    <AssemblyName>Project-Agil</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app-light.ico</ApplicationIcon>
    <Product>Project-Agil</Product>
    <Company>Project-Agil</Company>
    <AssemblyTitle>Project-Agil</AssemblyTitle>
    <Description>Free local network optimizer for Minecraft PvP</Description>
    <BuildNumber Condition="'$(BuildNumber)' == ''">0</BuildNumber>
    <Version>$(BuildNumber).0.0</Version>
    <FileVersion>$(BuildNumber).0.0.0</FileVersion>
    <AssemblyVersion>$(BuildNumber).0.0.0</AssemblyVersion>
    <InformationalVersion>b$(BuildNumber)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Copyright>Project-Agil</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" SubType="Designer" Generator="MSBuild:Compile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.3.0" />
    <PackageReference Include="WPF-UI.Tray" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app-light.ico" />
    <Resource Include="Assets\app-dark.ico" />
  </ItemGroup>

</Project>
